### ISSUE TITLE
Report Module

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#20] opened 2018-01-09 16:56 UTC
Provide a report module for dataset and resources in the catalog. The aim is to know:

- number of resources by format
- list of broken links 
- how many datasets published
- how many resources published

We should consider to use the [ckanext-report](https://github.com/datagovuk/ckanext-report) extension and configure the needed reports.

Some real cases linked below:

- https://data.gov.uk/data/report
- http://dati.toscana.it/report

**Comment by cezio** [comment] 2018-02-05 17:15
Could you elaborate more about broken links? Do you mean links to resources that doesn't work, links to remote datasets that doesn't work or datasets/resources reported as broken during harvesting?

**Comment by tdipisa** [comment] 2018-02-05 17:29
@cezio as already discussed something like [that](https://data.gov.uk/data/report/broken-links)

**Comment by cezio** [comment] 2018-02-07 09:51
I've put together some preliminary working reports: https://github.com/geosolutions-it/ckanext-gsreport/pull/1#issuecomment-363708643

List of reports:
![image](https://user-images.githubusercontent.com/116021/35909745-c55b5860-0bf4-11e8-9db2-c44841b682a9.png)

Resource types report:
![image](https://user-images.githubusercontent.com/116021/35909603-6c7043be-0bf4-11e8-9a30-f80f4eafe0ea.png)

License report:
![image](https://user-images.githubusercontent.com/116021/35909580-55905008-0bf4-11e8-9c00-0f7d7d2f7e50.png)

Broken links report:
![image](https://user-images.githubusercontent.com/116021/35909547-416433ba-0bf4-11e8-9c98-66cce4422e8c.png)

 This one contains more information per row, because link can be broken in several ways. I've put some basic information in template, there's a bit more in json/csv payloads:

![image](https://user-images.githubusercontent.com/116021/35909721-ad99471e-0bf4-11e8-8e6e-8fe8782bc3a8.png)

Reports can be customized with template, also we could add some filtering, to limit items requested (for example, limit report to specific organization or dataset). This could be helpful especially in broken links report.

**Comment by tdipisa** [comment] 2018-02-07 14:05
@cezio 

I tested on [opendata-trento.geo-solutions.it](http://opendata-trento.geo-solutions.it/report) (ckan 2.5.2) and the installation seems  to works fine. Just some notes below:

1. I think we need to improve the broken links checking for [WMS resources](http://opendata-trento.geo-solutions.it/dataset/curve-number). In this dataset for example we have WMS resources that point to http://www.territorio.provincia.tn.it/ that's not a WMS URL.

2. I would like to have a nice Admin UI for report using cards like [this](https://data.gov.uk/data/report)

3. Please, in the [resource format report](http://opendata-trento.geo-solutions.it/report/resources-format) indicate the total amount of existing resources 

4. Please, check the broken links report. (Here)[http://opendata-trento.geo-solutions.it/report/broken-links] it seems that no broken links exist but (here)[http://opendata-trento.geo-solutions.it/dataset/aree-wifi-di-accesso-pubblico] we have some 'not found' (404) resources

Tested then in [provbz demo server](http://188.165.62.180/report)(ckan 2.4.0) . Some notes below:

1. It seems that there ara problems in the (admin UI)[http://188.165.62.180/report] that need to be solved

**Comment by cezio** [comment] 2018-02-07 17:09
> I think we need to improve the broken links checking for WMS resources. In this dataset for example we have WMS resources that point to http://www.territorio.provincia.tn.it/ that's not a WMS URL.

True. This is however a link provided in resource. It will redirect to landing page with url to actual webgis site, when used in browser. Script will report this url as invalid, because in fact, it's not valid WMS endpoint.

**Comment by cezio** [comment] 2018-02-07 17:13
> Please, check the broken links report. (Here)[http://opendata-trento.geo-solutions.it/report/broken-links] it seems that no broken links exist but (here)[http://opendata-trento.geo-solutions.it/dataset/aree-wifi-di-accesso-pubblico] we have some 'not found' (404) resources

From notes in PR (https://github.com/geosolutions-it/ckanext-gsreport/pull/1#issuecomment-363708643): 

> **A word of caution:** reports may take longer time to generate (especially broken links, which will test each resource). To avoid timeouts in UI, reports should be generated from CLI (cron?) with `paster --plugin=ckanext-report report generate [optional name of report] --config=conf.ini command`.

**Comment by cezio** [comment] 2018-02-08 12:55
> I would like to have a nice Admin UI for report using cards like this

I've added styling with bootstrap 3.x (code was using classes from bs3, although actual css was deployed with different module in datagov's installation), just for this view:

![image](https://user-images.githubusercontent.com/116021/35973355-650de720-0cd5-11e8-9df9-77c0f2b02bed.png)

Layout is responsive, so narrow screen will look like this:

![image](https://user-images.githubusercontent.com/116021/35973936-89eab972-0cd7-11e8-82fd-4cce69af1d6c.png)

**Comment by tdipisa** [comment] 2018-02-08 14:33
@cezio 

**for point 1.**  I know that the URL per se is OK (the site landing page) but probably when you are going to check an OWS resource you should take into account the resource type. So, even if the URL is not broken, you should just to notify a warning for this in broken link section to keep the admin informed that the URL is ok but the type does not conresponds

**for point 2.**I installed your updates bu I cannot see any changes [here](http://opendata-trento.geo-solutions.it/report)

**for point 3.** OK

**for point 4.** I already run the paster command but there's not broken links notified [here](http://opendata-trento.geo-solutions.it/report/broken-links)

**Comment by cezio** [comment] 2018-02-08 15:25
> **for point 2.**I installed your updates bu I cannot see any changes here

Should work now. Slight misconfiguration, `status_reports` plugin should be before `report`. README is updated.

**Comment by cezio** [comment] 2018-02-08 15:33
> for point 1. I know that the URL per se is OK (the site landing page) but probably when you are going to check an OWS resource you should take into account the resource type. So, even if the URL is not broken, you should just to notify a warning for this in broken link section to keep the admin informed that the URL is ok but the type does not conresponds

So, what workflow should be used here? If we have resource with one of OWS formats, we should check if it's valid OWS endpoint, and if not, mark it as non-ows and do regular http check (and optionally mark it as invalid http endpoint if that also fails)?

**Comment by tdipisa** [comment] 2018-02-08 17:35
@Cezio yes

**Comment by cezio** [comment] 2018-02-09 10:50
For the record, I see few fields for improvement in reports:
 * we can add per-dataset or per-organization filtering
 * for broken-links report:
  * requests could be cached (urls can be duplicated in datasets, especially when they refer to non-ckan resources, like webgis portals, where one url is used as access gate to multiple resources)
  * requests could be parallelized to speed-up report generation (with multiprocessing module probably)
  * to avoid multiple instances of report generation running in cron (especially broken links), report generation should use lock.

**Comment by cezio** [comment] 2018-02-09 16:11
I've updated ckanext-gsreport, as requested. If OWS check will fail, regular http check is performed. If it success, resource will be marked with message:

![image](https://user-images.githubusercontent.com/116021/36037110-026d10ae-0dbc-11e8-83bb-811c6a1b42c9.png)

**Comment by tdipisa** [comment] 2018-02-12 11:33
@cezio,

there are problems while generating the broken link report in http://opendata-trento.geo-solutions.it/, below the link to the ckan.log file that you can also find in the related VM:

https://demo.geo-solutions.it/share/provinciabz/ckan.log

I think we need to properly manage timeouts, in any case I think you should investigate this in the demo instance.

As far as you can see, in that log we have also the strange logs I mentioned some days ago that need to be solved (see the top of the file), some fragments below:

+ set -h
+ VENV=/usr/local/app_loc/geosolutions/
+ DATAPUSHER_ROOT=/usr/local/data_loc/src/datapusher/datapusher
+ CONFIG=/usr/local/app_loc/geosolutions//conf/datapusher_settings.py
+ PYTHON_B=/usr/local/app_loc/geosolutions//bin/python
+ source /usr/local/app_loc/geosolutions//bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /bin/bash ']'

...

  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

Then there are still problems in the Reports UI, inside the provbz demo [here](http://188.165.62.180/report) that needs to be investigated.

Below the log reported running the **generate** command in provbz demo:

(default)[ckan@bolzano src]$ paster --plugin=ckanext-report report generate  --config=/etc/ckan/default/production.ini
2018-02-12 12:23:51,804 INFO  [ckanext.geonetwork.harvesters.geonetwork] GeoNetwork harvester: extending ISODocument with TimeInstant
2018-02-12 12:23:51,804 INFO  [ckanext.geonetwork.harvesters.geonetwork] GeoNetwork harvester: adding old GML URI
2018-02-12 12:23:51,805 INFO  [ckanext.geonetwork.harvesters.geonetwork] Added old URI for gml to temporal-extent-begin
2018-02-12 12:23:51,805 INFO  [ckanext.geonetwork.harvesters.geonetwork] Added old URI for gml to temporal-extent-begin
2018-02-12 12:23:51,805 INFO  [ckanext.geonetwork.harvesters.geonetwork] Added old URI for gml to temporal-extent-end
2018-02-12 12:23:51,805 INFO  [ckanext.geonetwork.harvesters.geonetwork] Added old URI for gml to temporal-extent-end
2018-02-12 12:23:51,805 INFO  [ckanext.geonetwork.harvesters.geonetwork] Added old URI for gml to temporal-extent-instant
2018-02-12 12:23:51,810 INFO  [ckanext.multilang.harvesters.multilang] CSW Multilang harvester: extending ISODocument with PT_FreeText
/usr/lib/ckan/default/src/ckan/ckan/new_authz.py:6: FutureWarning: ckan.new_authz has been renamed to ckan.authz. The ckan.new_authz module will be removed in a future release.
  FutureWarning)
2018-02-12 12:23:51,817 INFO  [rdflib] RDFLib Version: 4.2.1
2018-02-12 12:23:52,327 INFO  [ckan.lib.cli] Report generation complete {'All Reports': 3.0994415283203125e-06}

**Comment by cezio** [comment] 2018-02-12 11:45
> there are problems while generating the broken link report in http://opendata-trento.geo-solutions.it/,

 If you mean timeout when opening report, it's because broken links will take time to generate (described in readme and in PR notes). I'll add it to cron, so it will be generated once a day. If it's some other problem, please describe it in more detail.

> set -h
VENV=/usr/local/app_loc/geosolutions/
DATAPUSHER_ROOT=/usr/local/data_loc/src/datapusher/datapusher
CONFIG=/usr/local/app_loc/geosolutions//conf/datapusher_settings.py
PYTHON_B=/usr/local/app_loc/geosolutions//bin/python
source /usr/local/app_loc/geosolutions//bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /bin/bash ']'
...
File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
self.socket.bind(self.server_address)
File "/usr/local/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

This has nothing to do with reports module. This is probably because datapusher was run manually, and not stopped before running it as supervisord's service.

> Then there are still problems in the Reports UI, inside the provbz demo here that needs to be investigated.
2018-02-12 12:23:52,327 INFO [ckan.lib.cli] Report generation complete {'All Reports': 3.0994415283203125e-06}

 Again, look at provided readme and notes. There's no `status_reports` plugin in `ckan.plugins`

**Comment by tdipisa** [comment] 2018-02-12 12:16
@cezio 
the first time I installed the gsreport in http://opendata-trento.geo-solutions.it
the report generation was completed quickly with none of the messages I have now in the log (however, there was no broken link in the report that time).

I just need to understand if these log I have now are normal or not (ok for configuring a cron in both machines)

I now that the log I reported about datapusher is not related to gsreport but should be solved in any case.

About the provbz demo UI report, sorry my fault. However some screenshot below:

![resources_report.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46fa91892c9791aa8afa8051a14dff863d046b313916ac217586f76ae5002e005a5a1bf8475e5747fcf1dd22a6b63a71880d58b9853c4d68d47f40f2ecdd42e64bef62994597b7b4804dc5e93521e48c8a463f18031d9bb2.png)

**Comment by cezio** [comment] 2018-02-12 12:19
> However some screenshot below:

Thx. This looks like empty format in Resource. There are two cases actually. One is empty string, other is None  (I'm not sure if it's stringified `None`, or converted `NULL` from db). How should this be handled in reports?

**Comment by tdipisa** [comment] 2018-02-12 12:34
@cezio, In my opinion that should be handled ad **not specified**

**Comment by tdipisa** [comment] 2018-02-12 12:44
@cezio, about your improvement suggestions:

_we can add per-dataset or per-organization filtering_

Can we provide a per-organization filtering now? Something like provided [here](https://data.gov.uk/data/report/broken-links)

_if report fails during generation, it should leave some trace. Currently all work during generation is discarded, if for some reason report generation fails_

That's not reported in the usual ckan's log file?

_requests could be cached (urls can be duplicated in datasets, especially when they refer to non-ckan resources, like webgis portals, where one url is used as access gate to multiple resources)_

Can you provide an example?

_requests could be parallelized to speed-up report generation (with multiprocessing module probably)_

Not needed at this time but could be a nice improvement for the future

_to avoid multiple instances of report generation running in cron, report generation should use lock_

for the moment just one cron with a command that generates all reports in the same time is fine:

paster --plugin=ckanext-report report generate  --config=conf.ini

_filtering report by error type, resource type_

Can this be doable now within the issue's size we have? I need to check the available time on this

**Comment by cezio** [comment] 2018-02-12 13:31
> @cezio, In my opinion that should be handled ad not specified

Fixed in https://github.com/cezio/ckanext-gsreport/commit/5ac2a43c9c56bed83651ae2ca8670e98e8b400fb

**Comment by cezio** [comment] 2018-02-12 14:16
> @cezio, about your improvement suggestions:
>> we can add per-dataset or per-organization filtering
> Can we provide a per-organization filtering now? Something like provided here

Yes, I can add this. Fix in progress.

>> if report fails during generation, it should leave some trace. Currently all work during generation is discarded, if for some reason report generation fails
> That's not reported in the usual ckan's log file?

 Yes, but it won't be shown in reports UI. Admin won't know report has failed until logs are checked. This will cause some problems for users as well. User will click on report, which will start to generate (since there's no report saved), and get 500 error instead of meaningful message.

 This could be improved by extending report extension, catching error, and save report with message that it failed for specific reason. User would be still free to regenerate it from UI.

>> requests could be cached (urls can be duplicated in datasets, especially when they refer to non-ckan resources, like webgis portals, where one url is used as access gate to multiple resources)
> Can you provide an example?

 Sure, in tests we had urls to geoportals like http://www.territorio.provincia.tn.it/ which are present in 19 resources, and there are multiple similar cases in db:
```
-[ RECORD 1 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
url   | http://www.provinz.bz.it/natur-raum/themen/landeskartografie.asp
count | 252
-[ RECORD 2 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
url   | http://www.provinz.bz.it/natur-raum/
count | 104
-[ RECORD 3 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
url   | http://www.provinz.bz.it/strassendienst/
count | 75
-[ RECORD 4 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
url   | http://www.provinz.bz.it/forst/
count | 42
```

 So, I suspect it's a real problem, especially when handling non-ckan datasets. Having responses cached during report generation would speed up report generation (we will get 1 connection timeout instead of 50 for example).

> > to avoid multiple instances of report generation running in cron, report generation should use lock
> for the moment just one cron with a command that generates all reports in the same time is fine:
> paster --plugin=ckanext-report report generate --config=conf.ini

 Yes, but this doesn't prevent from running multiple instances of script, and this may be a case for larger installations. We use test instances, where we have fairly small number of resources, so report can be generated within ~5-10 minutes for ~1-2k resources. This may be a problem for deployments with 300-400k+ resources active.

>> filtering report by error type, resource type

> Can this be doable now within the issue's size we have? I need to check the available time on this

 It should be similar to filtering by organization. I'll need few hours to implement.

**Comment by tdipisa** [comment] 2018-02-12 14:17
@cezio 
I updated the provbz demo and generated again the all reports. Now in resource format I have **not specified** = 921. If I click on the **not specified** link a list of resources is shown. It seems that something wrong because the first dataset (named **Catasto eventi: eventi di frana**), for example, has two resources one in CSV format and one in WMS (the same for the other resources whitin listed dataset)

**Comment by cezio** [comment] 2018-02-12 14:23
> I updated the provbz demo and generated again the all reports. Now in resource format I have not specified = 921. If I click on the not specified link a list of resources is shown. It seems that something wrong because the first dataset (named Catasto eventi: eventi di frana), for example, has two resources one in CSV format and one in WMS (the same for the other resources whitin listed dataset)

This is because url is probably not working correctly for searching empty values. Fix in progress.

**Comment by tdipisa** [comment] 2018-02-12 14:26
@cezio, I understand your points. Please open new issues in gsreport for each point you reported with an exhaustive description in it and finally mark these as enhancement label. We will check later if we need to work on these issues.

**Comment by cezio** [comment] 2018-02-13 12:24
> For the moment please work only the following:
1 - per-organization filtering
2 - url is probably not working correctly for searching empty values

Implemented. See notes in linked issues (geosolutions-it/ckanext-gsreport#4 and geosolutions-it/ckanext-gsreport#3)

**Comment by tdipisa** [comment] 2018-02-16 14:40
@cezio, below some reviews after my checks on your work.

Checks has been performed in provbz demo [here](http://188.165.62.180/report):

**TRAVIS BUILD**

Should be fixed, it seems that the requirements.txt file has a wrong content

**RESOURCE FORMAT COUNTS**

1 - 'not specified': we have 910 of these (I think these are related 
to all of resorces named  **Unnamed resource**). However, if I click 
on the link the dataset list is empty.

2 - 'WMS': we have 267 of these but the count in Facet list is 251. However 
if i clink in the link the dataset list contains 251 dataset that's correct

3 - 'HTML': we have 6 of these but the count in Facet list is 2. However 
if i clink in the link the dataset list contains 2 dataset that's correct

4 - 'CSV': we have 3 of these but the count in Facet list is 2. However 
if i clink in the link the dataset list contains 2 dataset that's correct

5 - 'XLSX': we have 2 of these but the count in Facet list is 1. However 
if i clink in the link the dataset list contains 1 dataset that's correct

6 - 'PDF': we have 2 of these but the count in Facet list is 1. However 
if i clink in the link the dataset list contains 1 dataset that's correct

7 - If I access the report page using the localized path like the following:

http://188.165.62.180/it/report/resources-format

then I have a NOT FOUND error filtering by organizzation:

http://188.165.62.180/it/it/report/resources-format/pab-agricoltura

the same if I clink on **Refresh** button

**LICENSES COUNT**

1 - 'notspecified': please correct the lable using 'not specified'

2 - If I access the report page using the localized path like the following:

http://188.165.62.180/it/report/licenses

then I have a NOT FOUND error filtering by organizzation:

http://188.165.62.180/it/it/report/licenses/pab-agricoltura

the same if I clink on **Refresh** button 

**BROKEN LIKNS**

1 - If I access the report page using the localized path like the following:

http://188.165.62.180/it/report/broken-links

then I have a NOT FOUND error filtering by organizzation:

http://188.165.62.180/it/it/report/broken-links/pab-agricoltura

the same if I clink on **Refresh** button

2 - For some resources I see a correct report like the following :

![broken_link1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46ea869528878d9683e0b148f51fbcd6395428792c07b7692ac7b629ea177e05595946af41500b4dfcf98f2aa4e76f24de0d19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bd824bc9e9352ce08c89492c53.png)

But for other resources I have the following:

![broken_link2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46ea869528878d9683e0b148f61fbcd6395428792c07b7692ac7b629ea177e05595946af41500b4dfcf98f2aa4e76f24de0d19f1c32f0e2a92624cf5f2d75dad0ba821824584b3bd824bc9e93427e08c87462c53.png)

where ther OWS exception response is the same:

![broken_link3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46ea869528878d9683e0b148f71fbcd6395428792c07b7692ac7b629ea177e05595946af41500b4dfcf98f2aa4e76f24de0d19f1c32f0e2a92624cf5f2d75dad0ba8228b4584b3bd824bc9e93421ef8d8b4f2c53.png)

**REPORTS  VISUALIZATION**

1 - Only the admin user can access the /report endpoint

**README**

1 - We need to put a documentation to know that we can set a cron job for the report generate command

2 - We need to put a documentation that explain some useful information about the report core functionalities
and behaviors, for example:

- the report generation time depends on how fast is network and how fast resources are responding

- all the records in DB are replaced with the new ones but after succesful generation afair so if report generation fails, old data will be preserved

- how an user can be autorized to view a report

- the report will be generated if there's no prior data otherwise, user will see calculated result
	
- user can click 'refresh', and then report will be regenerated

**Comment by tdipisa** [comment] 2018-02-16 15:35
@cezio, an additional review below:

The report generation process on http://opendata-trento.geo-solutions.it 
closes with an exception, below the generated error that should be investigated:

Traceback (most recent call last):
  File "/usr/local/app_loc/geosolutions/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/command.py", line 66, in command
    self._generate(report_list)
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/command.py", line 110, in _generate
    registry.refresh_cache_for_all_reports()
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/report_registry.py", line 212, in refresh_cache_for_all_reports
    report.refresh_cache_for_all_options()
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/report_registry.py", line 81, in refresh_cache_for_all_options
    self.refresh_cache(option_dict)
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/report_registry.py", line 91, in refresh_cache
    data = self.generate(**option_dict)
  File "/usr/local/data_loc/src/ckanext-gsreport/ckanext/gsreport/reports.py", line 71, in report_broken_links
    out = check_url(res)
  File "/usr/local/data_loc/src/ckanext-gsreport/ckanext/gsreport/checkers.py", line 101, in check_url
    resp = handler(res, res_url)
  File "/usr/local/data_loc/src/ckanext-gsreport/ckanext/gsreport/checkers.py", line 220, in check_http
    resp = urlopen(res_url)
  File "/usr/local/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/local/lib/python2.7/urllib.py", line 180, in open
    fullurl = unwrap(toBytes(fullurl))
  File "/usr/local/lib/python2.7/urllib.py", line 1055, in toBytes
    " contains non-ASCII characters")
UnicodeError: URL u'http://www.statweb.provincia.tn.it/indicatoristrutturalisubpro/exp.aspx?ntab=Sub_Abitazioni_in_Propriet\xe0&info=md&fmt=csv' contains non-ASCII characters
You have mail in /var/spool/mail/geosolutions

**Comment by cezio** [comment] 2018-02-16 15:47
> TRAVIS BUILD

Should be fixed

> RESOURCE FORMAT COUNTS
> 1 - 'not specified': we have 910 of these (I think these are related
to all of resorces named Unnamed resource). However, if I click
on the link the dataset list is empty.

This was because solr index should be rebuilded after using this plugin (there was a comment in source issue, but I'll add this to readme. reindex will add `not-specified` placeholder to solr data, so those items will be searchable). I've run index rebuild on that vm.

> 2 - 'WMS': we have 267 of these but the count in Facet list is 251. However
if i clink in the link the dataset list contains 251 dataset that's correct
...
> 6 - 'PDF': we have 2 of these but the count in Facet list is 1. However
if i clink in the link the dataset list contains 1 dataset that's correct

All above are because report shows number of resources, and facets shows number of datasets found. I can add dataset count column to reports so it will be clear from where this number comes.

> 7 - If I access the report page using the localized path like the following:
http://188.165.62.180/it/report/resources-format
then I have a NOT FOUND error filtering by organizzation:
http://188.165.62.180/it/it/report/resources-format/pab-agricoltura

Notice bad `/it/it/` prefix in path. Fix in progress.

> LICENSES COUNT
> 1 - 'notspecified': please correct the lable using 'not specified'

This is because specific dataset (http://188.165.62.180/dataset/test-dataset) has 'notspecified' license set.


Rest in progress.

**Comment by cezio** [comment] 2018-02-16 16:11
>> 7 - If I access the report page using the localized path like the following:
http://188.165.62.180/it/report/resources-format
then I have a NOT FOUND error filtering by organizzation:
http://188.165.62.180/it/it/report/resources-format/pab-agricoltura
> Notice bad /it/it/ prefix in path. Fix in progress.

Actually this may be harder to fix. It looks like this is a bug in ckan, where 'redirect_to()` add language prefix to stringified url.

Basically, when you select option in form, form is submited with url:

Request URL:http://188.165.62.180/de/report/resources-format/comune-bolzano-sistema-informativo-territoriale?organization=provincia-autonoma-di-bolzano-alto-adige-astat

This hits `ckanext.report.controllers`: https://github.com/datagovuk/ckanext-report/blob/master/ckanext/report/controllers.py#L43-L46

And returns redirection to `/en/report/resources-format/org1` (this is result of `toolkit.url_for()` from https://github.com/datagovuk/ckanext-report/blob/master/ckanext/report/helpers.py#L25). And this is where `redirect_to()` adds lang code to redirected url.

**Comment by tdipisa** [comment] 2018-02-16 17:03
@cezio, please remove also the double colon in org filter:

![broken_link4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46ea869528878d9683e0b148f01fbcd6395428792c07b7692ac7b629ea177e05595946af41500b4dfcf98f2aa4e76f24de0d19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bd8244c0e83823ef88884b2c53.png)

**Comment by cezio** [comment] 2018-02-16 17:07
> @cezio, please remove also the double colon in org filter:

There is no `Organization :` string in translation in `ckanext-gsreport`. Can this come from i18n from other extension?

**Comment by cezio** [comment] 2018-02-16 17:15
> @cezio, please remove also the double colon in org filter:

Addressed with https://github.com/cezio/ckanext-gsreport/commit/33a52a658cb8a8dd769afde01af06a8db3995575

**Comment by cezio** [comment] 2018-02-16 18:05
>  Only the admin user can access the /report endpoint

Addressed with https://github.com/cezio/ckanext-gsreport/commit/1c2fa79f400ec72fa0ea59c4b30198a4eeb38329. One note here: implementation is a bit hackish, because ckan dissalow auth functions override once they are defined. In this case, our plugin defines auth functions first, `report` does it again, so to avoid exception, I've replaced `IAuthFunctions.get_auth_functions` from `report` plugin, so it will return empty dict.

**Comment by tdipisa** [comment] 2018-03-07 11:43
@cezio,
thank you for your fixes. It seems that the PR is still missing. Some notes below:

**auth functions**
do we really need this hack? I would like to avoid it if possible.

from the ckan's doc: 

" ... Note that by default, all auth functions provided by extensions are assumed to require a validated user or API key, otherwise a ckan.logic.NotAuthorized: exception will be raised. This check will be performed before calling the actual auth function. If you want to allow anonymous access to one of your actions, its auth function must be decorated with the auth_allow_anonymous_access decorator, available on the plugins toolkit."

**redirect to** (double lang path in URL: /it/it)

has this behavior been fixed in new ckan's versions ?
Can we provide a patch for this in our extension ?

**travis build** 

has been fixed now ?

**Comment by tdipisa** [comment] 2018-03-07 12:07
@cezio, another most important issue here using your master branch. If I run the following command:

 paster --plugin=ckanext-report report generate --config=/usr/local/app_loc/geosolutions/conf/production.ini

the following error occurred both [here](http://opendata-trento.geo-solutions.it) and [here](http://188.165.62.180/):

Traceback (most recent call last):
  File "/usr/local/app_loc/geosolutions/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/command.py", line 66, in command
    self._generate(report_list)
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/command.py", line 110, in _generate
    registry.refresh_cache_for_all_reports()
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/report_registry.py", line 212, in refresh_cache_for_all_reports
    report.refresh_cache_for_all_options()
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/report_registry.py", line 81, in refresh_cache_for_all_options
    self.refresh_cache(option_dict)
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/report_registry.py", line 94, in refresh_cache
    key = self.generate_key(option_dict, defaults_for_missing_keys=False)
  File "/usr/local/data_loc/src/ckanext-report/ckanext/report/report_registry.py", line 58, in generate_key
    value = option_dict[key]
KeyError: 'dataset'

**Comment by cezio** [comment] 2018-03-09 12:23
> auth functions
do we really need this hack? I would like to avoid it if possible.

 If we want to allow only admin user, yes.
> from the ckan's doc:
" ... Note that by default, all auth functions provided by extensions are assumed to require a validated user or API key, otherwise a ckan.logic.NotAuthorized: exception will be raised. This check will be performed before calling the actual auth function. If you want to allow anonymous access to one of your actions, its auth function must be decorated with the auth_allow_anonymous_access decorator, available on the plugins toolkit."

 This says only about authenticated users, not admin-level users.


> redirect to (double lang path in URL: /it/it)
has this behavior been fixed in new ckan's versions ?
Can we provide a patch for this in our extension ?

This seems to be fixed in master: https://github.com/ckan/ckan/issues/3499
I'll check if we can backport this somehow to extension (i suspect that means monkey-patching url_for() implementation).

> travis build
It seems that the related PR from your master has some issues to solve in the travis build.

investigating.

**Comment by tdipisa** [comment] 2018-03-09 13:52
@cezio 
redirect to (double lang path in URL: /it/it): it seems just partially fixed. go to the following URL and then click on the refresh button:

http://188.165.62.180/it/report/resources-format

auth functions: maybe we can allow also authenticated user. I will do another check  before. thank you

travis build: ok, let me know.

**Comment by cezio** [comment] 2018-03-09 13:54
> redirect to (double lang path in URL: /it/it): it seems just partially fixed. go to the following URL and then click on the refresh button:

Checking.

**Comment by cezio** [comment] 2018-03-09 13:57
> @cezio, another and most important issue here using your master branch. If I run the following command:
> the following error occurred both here and here:

should be fixed

> redirect to (double lang path in URL: /it/it): it seems just partially fixed. go to the following URL and then click on the refresh button:

This was probably because code for gsreport extension was not updated. i've updated to latest master, seems to work, but please confirm.

**Comment by tdipisa** [comment] 2018-03-09 15:14
@cezio see the following from my tests yesterday:

![issue.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46e187893687c1e5cdf9ad4cae58f3806b1c65262851f62e74d3b570ec122305565f4eaa405a0e17a8add839baa47e21d40854b088270a36d43703adbf881eba03ba268b4781bebc8d4bc9fa70.gif

**Comment by tdipisa** [comment] 2018-03-09 15:18
@cezio what about my comment [here](https://github.com/geosolutions-it/ckanext-provbz/issues/20#issuecomment-371118350)? What you did for fixing the problem?

**Comment by cezio** [comment] 2018-03-09 15:20
> @cezio see the following from my tests yesterday:

Thx. I can reproduce. fix in progress.

**Comment by cezio** [comment] 2018-03-09 15:22
> @cezio what about my comment here? What you did for fixing the problem?

Fix for this is a part of PR: https://github.com/geosolutions-it/ckanext-gsreport/pull/8/commits/b26161f67ea02f0b6da0329cc490d7ac7adbdbe4

**Comment by tdipisa** [comment] 2018-03-16 09:45
@cezio as we discussed:

1) now is not possible to change the language from the drop down in the footer

2) please check if possible to apply a quick patch to our extension to solve the redirect_to remaining issues , if not possible pleade hide the refresh button. 

3) if you hide the refresh button please update also the invoved part on the readme documentation.

4) After the points above I will proceed to a new check to merge the pull requests (I will close #7 and #8 whithout merging them). I think you can direclty include the translations updates in #7 in the PR #9 ok?

**Comment by cezio** [comment] 2018-03-16 11:05
> if you hide the refresh button please update also the invoved part on the readme documentation.

button removed, readme updated.

**Closed** 2018-03-16 11:34 UTC
Labels: MEV, Project: C029, Project: C054, enhancement, investigation, pending review, review
